name: firebase_performance_dio
description: Dio Firebase performance monitoring.
version: 0.5.0
homepage: https://github.com/darkxanter/firebase_performance_dio

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  firebase_performance: ">=0.8.0 <0.10.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
